# .streamlit/secrets.toml
GOOGLE_API_KEY = "AIzaSyDSrTS27xN2wqPa4Byt8-dOwXwY2RYBE20"
OPENAI_API_KEY = "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" 